[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
norecursedirs = scratch build dist .git __pycache__ .tempmediaStorage node_modules
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
